CREATE SEQUENCE TBL_CONTATOS_PROJECT_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_CONTATOS_PROJECT (
    ID INTEGER DEFAULT TBL_CONTATOS_PROJECT_SEQ.NEXTVAL NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) OT NULL,
    DATA_NASCIMENTO DATE NOT NULL
);