CREATE SEQUENCE CONTATO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_CONTATOS_PROJECT (
    ID INTEGER DEFAULT CONTATO_SEQ.NEXTVAL NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NULL,
    SENHA VARCHAR2(60) NULL,
    DATA_NASCIMENTO DATE NOT NULL
);
